# Config file for Air
root = "."
tmp_dir = "tmp"

[build]
  include_dir = ["cmd", "internal", "pkg"]
  cmd = "go build -o tmp/main ./cmd/server/."
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
